export const productData = [
  {
    category: "Fruits & Vegetables",
    id: "fruits",
    products: [
      {
        id: 1,
        name: "Apple",
        image: "/images/Veg/apple.avif",
        price: "120",
        quantity: "1 kg",
        time: "30 MINS",
      },
      {
        id: 2,
        name: "Banana",
        image: "/images/Veg/banana.avif",
        price: "70",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 3,
        name: "Carrot",
        image: "/images/Veg/gajar.avif",
        price: "20",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 4,
        name: "Cucumber",
        image: "/images/Veg/cucumber.avif",
        price: "30",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 5,
        name: "Curry",
        image: "/images/Veg/curry.avif",
        price: "10",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 6,
        name: "Alu",
        image: "/images/Veg/alu.avif",
        price: "40",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 7,
        name: "Garlic",
        image: "/images/Veg/garlic.avif",
        price: "40",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 8,
        name: "Mango",
        image: "/images/Veg/mango.avif",
        price: "100",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 9,
        name: "Onion",
        image: "/images/Veg/onion.avif",
        price: "40",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 10,
        name: "Watermilon",
        image: "/images/Veg/tarbooj.avif",
        price: "25",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 11,
        name: "Tomato",
        image: "/images/Veg/tomato.avif",
        price: "25",
        quantity: "1 kg",
        time: "20 MINS",
      },
      {
        id: 12,
        name: "Corn",
        image: "/images/Veg/corn.avif",
        price: "25",
        quantity: "1 kg",
        time: "20 MINS",
      },
    ],
  },
  {
    category: "Dairy, Bread & Eggs",
    id: "dairy",
    products: [
      {
        id: 1,
        name: "Nandini Curd",
        image: "/images/Dairy/curd.avif",
        price: "30",
        quantity: "500 ml",
        time: "30 MINS",
      },
      {
        id: 2,
        name: "Amul Butter",
        image: "/images/Dairy/amul.avif",
        price: "30",
        quantity: "100 gm",
        time: "30 MINS",
      },
      {
        id: 3,
        name: "White Egg",
        image: "/images/Dairy/Egg.avif",
        price: "60",
        quantity: "6",
        time: "30 MINS",
      },
      {
        id: 4,
        name: "Nandani Milk",
        image: "/images/Dairy/milk.avif",
        price: "24",
        quantity: "500 ml",
        time: "30 MINS",
      },
      {
        id: 5,
        name: "Milk",
        image: "/images/Dairy/milk2.avif",
        price: "10",
        quantity: "100 ml",
        time: "30 MINS",
      },
      {
        id: 6,
        name: "Wheat Bread",
        image: "/images/Dairy/wheat-bread.avif",
        price: "50",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 7,
        name: "Bread",
        image: "/images/Dairy/bread.avif",
        price: "30",
        quantity: "1 pc",
        time: "30 MINS",
      },
    ],
  },
  {
    category: "Drinks & Juices",
    id: "drinks",
    products: [
      {
        id: 1,
        name: "Coco-cola",
        image: "/images/Drink/coco-cola.avif",
        price: "50",
        quantity: "500 ml",
        time: "30 MINS",
      },
      {
        id: 2,
        name: "Bislery",
        image: "/images/Drink/bislery.avif",
        price: "20",
        quantity: "1 lt",
        time: "30 MINS",
      },
      {
        id: 3,
        name: "Frooti",
        image: "/images/Drink/frooti.avif",
        price: "10",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 4,
        name: "Coka",
        image: "/images/Drink/coka.avif",
        price: "25",
        quantity: "500 ml",
        time: "30 MINS",
      },
      {
        id: 5,
        name: "Ice-cube",
        image: "/images/Drink/ice-cube.avif",
        price: "20",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 6,
        name: "Maza",
        image: "/images/Drink/maza.avif",
        price: "60",
        quantity: "1 lt",
        time: "30 MINS",
      },
      {
        id: 7,
        name: "Sprite",
        image: "/images/Drink/sprite.avif",
        price: "30",
        quantity: "500 ml",
        time: "30 MINS",
      },
      {
        id: 8,
        name: "Water",
        image: "/images/Drink/water.avif",
        price: "50",
        quantity: "5 lt",
        time: "30 MINS",
      },
    ],
  },
  {
    category: "Snacks & Munchies",
    id: "snacks",
    products: [
      {
        id: 1,
        name: "bread",
        image: "/images/Snacks/bread.avif",
        price: "30",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 2,
        name: "Hot Chips",
        image: "/images/Snacks/hotchips.avif",
        price: "20",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 3,
        name: "Namkeen",
        image: "/images/Snacks/Namkeen.avif",
        price: "15",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 4,
        name: "Pop Corn",
        image: "/images/Snacks/popcorn.avif",
        price: "35",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 5,
        name: "Puff",
        image: "/images/Snacks/puff1.avif",
        price: "10",
        quantity: "1 pc",
        time: "30 MINS",
      },
      {
        id: 6,
        name: "Hot Puff",
        image: "/images/Snacks/puff2.avif",
        price: "20",
        quantity: "1 pc",
        time: "30 MINS",
      },
    ],
  },
];
